version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "for-qa"
    target-branch: "for-qa"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
