// Branded HVE email templates for the procurement approval flow (Mainspring green).
const GREEN = '#2b6450'

function shell(headerTitle: string, headerSub: string, bodyInner: string, clientName: string): string {
  return `<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office"><body style="margin:0;padding:0"><table cellpadding="0" cellspacing="0" width="100%" style="font-family:Arial,sans-serif;background-color:#f4f6f8;padding:24px"><tr><td align="center"><table cellpadding="0" cellspacing="0" width="620" style="background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 6px rgba(0,0,0,0.08)"><tr><td style="padding:20px;background:${GREEN};color:#ffffff;text-align:left"><h2 style="margin:0;font-size:18px;font-weight:600">${headerTitle}</h2><div style="font-size:12px;opacity:0.95">${headerSub}</div></td></tr><tr><td style="padding:20px;color:#333333;font-size:14px;line-height:1.5">${bodyInner}</td></tr><tr><td style="padding:12px 20px;background:#f7f9fb"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="left" style="font-size:12px;color:#666">Procurement · ${clientName || 'Mainspring Recovery'}</td><td align="right" style="font-size:12px;color:#666">Automated Summary</td></tr></table></td></tr></table></td></tr></table></body></html>`
}

export interface ApprovedItem { name: string; qty: string; dept: string; location: string; approvedBy: string; url: string | null }
export function buildApprovedEmail(o: { requester: string; items: ApprovedItem[]; recordsUrl: string; purchasingUrl: string; clientName: string; approverName: string }): string {
  const th = 'border:1px solid #e6e9ed;padding:8px;font-weight:600;text-align:left;background-color:#dbf0e9;color:#1f4739'
  const td = 'padding:8px;border:1px solid #e6e9ed'
  const rows = o.items.map((it) => `<tr><td style="${td}">${it.name}</td><td style="${td}">${it.qty}</td><td style="${td}">${it.dept}</td><td style="${td}">${it.location}</td><td style="${td}">${it.approvedBy}</td><td style="${td}">${it.url ? `<a href="${it.url}" target="_blank" style="color:${GREEN};text-decoration:none">View Item</a>` : '—'}</td></tr>`).join('')
  const body = `<p style="margin:0 0 12px 0">Good day,</p><p style="margin:0 0 12px 0">Requested by: <strong>${o.requester}</strong></p><p style="margin:0 0 16px 0">The following items have been <strong>approved</strong> for purchase:</p><table cellpadding="6" cellspacing="0" width="100%" style="border-collapse:collapse;border:1px solid #e6e9ed;font-size:13px"><thead><tr><th style="${th}">Item</th><th style="${th}">Quantity</th><th style="${th}">Department</th><th style="${th}">Location</th><th style="${th}">Approved By</th><th style="${th}">URL</th></tr></thead><tbody>${rows}</tbody></table>${o.recordsUrl ? `<p style="margin:20px 0 12px 0">You can view the complete item list here:</p><p style="margin:0 0 16px 0"><a href="${o.recordsUrl}" target="_blank" style="color:${GREEN};text-decoration:none;font-weight:600">View full item list</a></p>` : ''}${o.purchasingUrl ? `<p style="margin:0 0 12px 0">Once you've confirmed the expected delivery details, please set the <strong>ETA</strong> and <strong>Shipping Location</strong>:</p><p style="margin:0 0 16px 0"><a href="${o.purchasingUrl}" target="_blank" style="color:${GREEN};text-decoration:none;font-weight:600">Set ETA &amp; shipping (Purchasing)</a></p>` : ''}<p style="margin-top:18px;font-size:12px;color:#666">For any updates or clarifications, please reach out to ${o.approverName || 'the approver'}.</p>`
  return shell('Approved Procurement Request', 'Items approved for purchase', body, o.clientName)
}

export interface SummaryItem { name: string; status: string; comments: string; decidedBy: string; returnUrl: string | null; canReturn: boolean }
export function buildSummaryEmail(o: { items: SummaryItem[]; clientName: string; approverName: string }): string {
  const th = 'border:1px solid #e6e9ed;padding:8px;font-weight:600;text-align:left;background-color:#dbf0e9;color:#1f4739'
  const thc = th + ';text-align:center'
  const td = 'padding:8px;border:1px solid #e6e9ed'
  const rows = o.items.map((it) => `<tr><td style="${td}">${it.name}</td><td style="${td}">${it.status}</td><td style="${td};word-break:break-word">${it.comments}</td><td style="${td}">${it.decidedBy}</td><td style="${td};text-align:center">${it.canReturn && it.returnUrl ? `<a href="${it.returnUrl}" target="_blank" style="display:inline-block;padding:6px 12px;background-color:${GREEN};color:#ffffff;text-decoration:none;border-radius:4px;font-size:12px;font-weight:600">Return</a>` : '—'}</td></tr>`).join('')
  const body = `<p style="margin:0 0 12px 0">Kindly review your request summary. For any denied requests, please submit a new request addressing the approver's comments.</p><p style="margin:0 0 16px 0">Below is the summary of items included in this purchase request and their current approval status:</p><table cellpadding="6" cellspacing="0" width="100%" style="border-collapse:collapse;border:1px solid #e6e9ed;font-size:13px"><thead><tr><th style="${th}">Item</th><th style="${th}">Status</th><th style="${th}">Comments</th><th style="${th}">Approved/Denied By</th><th style="${thc}">Action</th></tr></thead><tbody>${rows}</tbody></table><p style="margin-top:18px;font-size:12px;color:#666">For any updates or clarifications, please reach out to ${o.approverName || 'the approver'}.</p>`
  return shell('Request Summary', 'Overview of submitted items', body, o.clientName)
}
