-- Owner of new requests defaults to the caller (used by RLS).
ALTER TABLE purchase_requests ALTER COLUMN requester_id SET DEFAULT auth.uid();

-- Aggregate helper: set purchase_requests.status from its line items.
CREATE OR REPLACE FUNCTION internal.proc_recompute_request_status(p_request_id uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = app_procurement, public AS $fn$ DECLARE n int; n_decl int; n_pend int; n_appr int; n_hold int; BEGIN SELECT count(*), count(*) FILTER (WHERE status='declined'), count(*) FILTER (WHERE status='pending'), count(*) FILTER (WHERE status IN ('approved','ordered','received','returned','replacement_ordered')), count(*) FILTER (WHERE status='on_hold') INTO n, n_decl, n_pend, n_appr, n_hold FROM app_procurement.line_items WHERE request_id = p_request_id; UPDATE app_procurement.purchase_requests SET status = CASE WHEN n=0 THEN 'pending' WHEN n_decl=n THEN 'declined' WHEN n_pend=n THEN 'pending' WHEN n_hold>0 AND n_appr=0 THEN 'on_hold' WHEN n_pend=0 AND n_hold=0 AND n_appr>0 THEN 'approved' WHEN n_appr>0 THEN 'partially_approved' ELSE 'pending' END, updated_at = now() WHERE id = p_request_id; END; $fn$;

-- submit_request: create request (caller is requester) + insert line items from a JSON array.
CREATE OR REPLACE FUNCTION app_procurement.submit_request(p_notes text, p_line_items jsonb) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path = app_procurement, public AS $fn$ DECLARE v_id uuid; li jsonb; BEGIN IF NOT public.check_user_permission(auth.uid(), 'apps/procurement/requests/create') THEN RAISE EXCEPTION 'Not permitted to create requests'; END IF; INSERT INTO app_procurement.purchase_requests (requester_id, requester_type, submission_source, status, notes, submitted_at) VALUES (auth.uid(), 'portal_user', 'in_portal', 'pending', p_notes, now()) RETURNING id INTO v_id; FOR li IN SELECT * FROM jsonb_array_elements(coalesce(p_line_items, '[]'::jsonb)) LOOP INSERT INTO app_procurement.line_items (request_id, ship_to_name, location_id, custom_location, department_id, custom_department, item_url, item_description, memo, quantity, substitution_ok, date_needed, status) VALUES (v_id, li->>'ship_to_name', nullif(li->>'location_id','')::uuid, li->>'custom_location', nullif(li->>'department_id','')::uuid, li->>'custom_department', li->>'item_url', li->>'item_description', li->>'memo', coalesce((li->>'quantity')::int,1), coalesce((li->>'substitution_ok')::boolean,false), nullif(li->>'date_needed','')::date, 'pending'); END LOOP; RETURN v_id; END; $fn$;

-- decide_line_item: approver approves/declines/holds an item.
CREATE OR REPLACE FUNCTION app_procurement.decide_line_item(p_line_item_id uuid, p_action text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = app_procurement, public AS $fn$ DECLARE v_req uuid; BEGIN IF NOT public.check_user_permission(auth.uid(), 'apps/procurement/approvals/act') THEN RAISE EXCEPTION 'Not permitted to approve'; END IF; IF p_action NOT IN ('approved','declined','on_hold') THEN RAISE EXCEPTION 'Invalid action'; END IF; UPDATE app_procurement.line_items SET status = p_action, approved_by = auth.uid(), approval_date = now(), updated_at = now() WHERE id = p_line_item_id AND status IN ('pending','on_hold') RETURNING request_id INTO v_req; IF v_req IS NULL THEN RAISE EXCEPTION 'Item not found or not in a decidable state'; END IF; PERFORM internal.proc_recompute_request_status(v_req); END; $fn$;

-- order_line_item: purchaser records the order for an approved item.
CREATE OR REPLACE FUNCTION app_procurement.order_line_item(p_line_item_id uuid, p_date_purchased date, p_eta date, p_shipping_location_id uuid, p_custom_shipping_location text, p_purchase_notes text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = app_procurement, public AS $fn$ DECLARE v_req uuid; BEGIN IF NOT public.check_user_permission(auth.uid(), 'apps/procurement/purchasing/manage') THEN RAISE EXCEPTION 'Not permitted to purchase'; END IF; UPDATE app_procurement.line_items SET status='ordered', date_purchased=coalesce(p_date_purchased, current_date), eta=p_eta, shipping_location_id=p_shipping_location_id, custom_shipping_location=p_custom_shipping_location, purchase_notes=p_purchase_notes, updated_at=now() WHERE id=p_line_item_id AND status='approved' RETURNING request_id INTO v_req; IF v_req IS NULL THEN RAISE EXCEPTION 'Item not found or not approved'; END IF; PERFORM internal.proc_recompute_request_status(v_req); END; $fn$;

-- receive_line_item: the request owner marks an ordered item received.
CREATE OR REPLACE FUNCTION app_procurement.receive_line_item(p_line_item_id uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = app_procurement, public AS $fn$ DECLARE v_owner uuid; BEGIN SELECT pr.requester_id INTO v_owner FROM app_procurement.line_items li JOIN app_procurement.purchase_requests pr ON pr.id = li.request_id WHERE li.id = p_line_item_id; IF v_owner IS DISTINCT FROM auth.uid() AND NOT public.check_user_permission(auth.uid(), 'apps/procurement/admin/manage') THEN RAISE EXCEPTION 'Only the requester can mark received'; END IF; UPDATE app_procurement.line_items SET status='received', updated_at=now() WHERE id=p_line_item_id AND status='ordered'; END; $fn$;

-- initiate_return: the request owner returns a received item.
CREATE OR REPLACE FUNCTION app_procurement.initiate_return(p_line_item_id uuid, p_return_quantity int, p_return_reason text, p_has_packaging boolean, p_wants_replacement boolean, p_return_notes text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = app_procurement, public AS $fn$ DECLARE v_owner uuid; BEGIN SELECT pr.requester_id INTO v_owner FROM app_procurement.line_items li JOIN app_procurement.purchase_requests pr ON pr.id = li.request_id WHERE li.id = p_line_item_id; IF v_owner IS DISTINCT FROM auth.uid() AND NOT public.check_user_permission(auth.uid(), 'apps/procurement/admin/manage') THEN RAISE EXCEPTION 'Only the requester can initiate a return'; END IF; UPDATE app_procurement.line_items SET status='returned', return_quantity=p_return_quantity, return_reason=p_return_reason, has_packaging=p_has_packaging, wants_replacement=p_wants_replacement, return_notes=p_return_notes, return_date=now(), updated_at=now() WHERE id=p_line_item_id AND status='received'; END; $fn$;

-- process_return: purchaser resolves a return, optionally ordering a replacement.
CREATE OR REPLACE FUNCTION app_procurement.process_return(p_line_item_id uuid, p_order_replacement boolean) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = app_procurement, public AS $fn$ BEGIN IF NOT public.check_user_permission(auth.uid(), 'apps/procurement/returns/manage') THEN RAISE EXCEPTION 'Not permitted to process returns'; END IF; UPDATE app_procurement.line_items SET status = CASE WHEN p_order_replacement THEN 'replacement_ordered' ELSE status END, updated_at=now() WHERE id=p_line_item_id AND status='returned'; END; $fn$;

REVOKE ALL ON FUNCTION app_procurement.submit_request(text, jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION app_procurement.submit_request(text, jsonb) TO authenticated, service_role;
REVOKE ALL ON FUNCTION app_procurement.decide_line_item(uuid, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION app_procurement.decide_line_item(uuid, text) TO authenticated, service_role;
REVOKE ALL ON FUNCTION app_procurement.order_line_item(uuid, date, date, uuid, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION app_procurement.order_line_item(uuid, date, date, uuid, text, text) TO authenticated, service_role;
REVOKE ALL ON FUNCTION app_procurement.receive_line_item(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION app_procurement.receive_line_item(uuid) TO authenticated, service_role;
REVOKE ALL ON FUNCTION app_procurement.initiate_return(uuid, int, text, boolean, boolean, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION app_procurement.initiate_return(uuid, int, text, boolean, boolean, text) TO authenticated, service_role;
REVOKE ALL ON FUNCTION app_procurement.process_return(uuid, boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION app_procurement.process_return(uuid, boolean) TO authenticated, service_role;

-- Row-ownership RLS (fail-safe: DROP+recreate; INSERT left default — writes go through the DEFINER RPCs).
-- purchase_requests: requester sees own; approver/purchaser/admin see all (gated by holding any acting permission).
DROP POLICY IF EXISTS app_procurement_purchase_requests_read ON app_procurement.purchase_requests;
CREATE POLICY app_procurement_purchase_requests_read ON app_procurement.purchase_requests FOR SELECT TO authenticated USING (requester_id = auth.uid() OR public.check_user_permission(auth.uid(), 'apps/procurement/approvals/act') OR public.check_user_permission(auth.uid(), 'apps/procurement/purchasing/manage') OR public.check_user_permission(auth.uid(), 'apps/procurement/admin/manage'));

-- line_items: same visibility, via the parent request.
DROP POLICY IF EXISTS app_procurement_line_items_read ON app_procurement.line_items;
CREATE POLICY app_procurement_line_items_read ON app_procurement.line_items FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM app_procurement.purchase_requests pr WHERE pr.id = line_items.request_id AND (pr.requester_id = auth.uid() OR public.check_user_permission(auth.uid(), 'apps/procurement/approvals/act') OR public.check_user_permission(auth.uid(), 'apps/procurement/purchasing/manage') OR public.check_user_permission(auth.uid(), 'apps/procurement/admin/manage'))));
