-- 011: Phase 4 QA — cancel an approved item (terminal 'cancelled'); requester resubmits.
-- Widen both status CHECK constraints, teach the rollup about cancelled, add cancel_line_item.
ALTER TABLE app_procurement.line_items DROP CONSTRAINT IF EXISTS line_items_status_check;
ALTER TABLE app_procurement.line_items ADD CONSTRAINT line_items_status_check CHECK (status IN ('pending','approved','declined','on_hold','ordered','received','returned','replacement_ordered','cancelled'));
ALTER TABLE app_procurement.purchase_requests DROP CONSTRAINT IF EXISTS purchase_requests_status_check;
ALTER TABLE app_procurement.purchase_requests ADD CONSTRAINT purchase_requests_status_check CHECK (status IN ('pending','on_hold','partially_approved','approved','declined','cancelled'));
CREATE OR REPLACE FUNCTION internal.proc_recompute_request_status(p_request_id uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = app_procurement, public AS $fn$ DECLARE n int; n_canc int; n_decl int; n_pend int; n_appr int; n_hold int; n_eff int; BEGIN SELECT count(*), count(*) FILTER (WHERE status='cancelled'), count(*) FILTER (WHERE status='declined'), count(*) FILTER (WHERE status='pending'), count(*) FILTER (WHERE status IN ('approved','ordered','received','returned','replacement_ordered')), count(*) FILTER (WHERE status='on_hold') INTO n, n_canc, n_decl, n_pend, n_appr, n_hold FROM app_procurement.line_items WHERE request_id = p_request_id; n_eff := n - n_canc; UPDATE app_procurement.purchase_requests SET status = CASE WHEN n=0 THEN 'pending' WHEN n_eff=0 THEN 'cancelled' WHEN n_decl=n_eff THEN 'declined' WHEN n_pend=n_eff THEN 'pending' WHEN n_hold>0 AND n_appr=0 THEN 'on_hold' WHEN n_pend=0 AND n_hold=0 AND n_appr>0 THEN 'approved' WHEN n_appr>0 THEN 'partially_approved' ELSE 'pending' END, updated_at = now() WHERE id = p_request_id; END; $fn$;
CREATE OR REPLACE FUNCTION app_procurement.cancel_line_item(p_line_item_id uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = app_procurement, public AS $fn$ DECLARE v_req uuid; BEGIN IF NOT (public.check_user_permission(auth.uid(),'apps/procurement/approvals/act') OR public.check_user_permission(auth.uid(),'apps/procurement/purchasing/manage') OR public.check_user_permission(auth.uid(),'apps/procurement/admin/manage')) THEN RAISE EXCEPTION 'Not permitted to cancel'; END IF; UPDATE app_procurement.line_items SET status='cancelled', updated_at=now() WHERE id=p_line_item_id AND status='approved' RETURNING request_id INTO v_req; IF v_req IS NULL THEN RAISE EXCEPTION 'Item not found or not approved'; END IF; PERFORM internal.proc_recompute_request_status(v_req); END; $fn$;
REVOKE ALL ON FUNCTION app_procurement.cancel_line_item(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION app_procurement.cancel_line_item(uuid) TO authenticated, service_role;
